### ISSUE TITLE
CDJ error message on startup: "Linked to player with older firmware..."

### ISSUE THREAD

**Issue by mattpstv** [EvanPurkhiser/prolink-go#11]
After starting prolink-go and two CDJ-900nxs2s + DJM-900nxs2 + DJS-1000, both CDJs display the following message: "Linked to player with older firmware. Please update to latest version." I triple checked and all Pioneer units have most recent firmware. There doesn't seem to be any further issues related to this message (prolink-go performs as described). I also re-started prolink-go and just the two CDJs and DJM (and not the DJS) just in case there was something particular to the DJS that was causing the message but the same message appears. Screenshot attached. Let me know if you need any more info.
![firmware message on cdj-2000xnxs2 when using pro-link](https://user-images.githubusercontent.com/44700535/47965614-f044ba00-e00e-11e8-9f69-b955ffda172a.jpg)

**Comment by EvanPurkhiser** [comment]
Thanks @mattpstv! I've actually seen this error myself and had been disregarding it for now. I'll take a closer look.

**Comment by brunchboy** [comment]
…interesting, I will have to leave this in my inbox to remind me to check what my packet template has for those bytes.
